### ISSUE TITLE
Missing comment event from kubernetes/kubernetes

### ISSUE THREAD

**Issue by lukaszgryglicki** [igrigorik/gharchive.org#187]
@igrigorik I've detected missing comment event.
This [event](https://github.com/kubernetes/kubernetes/issues/59001#issuecomment-391073109) is not recorded in any JSON.
I've investigated [issue](https://github.com/cncf/devstats/issues/111) on my side, save all JSONs to files and grepped them for Issue ID, comment text etc.

Do you have any stats about how many events can be missing in github archives. Or maybe this is just a single case like this?

Thanks!
cc @dankohn, @jberkus

**Comment by lukaszgryglicki** [comment]
@igrigorik ping

**Comment by igrigorik** [comment]
@lukaszgryglicki thanks for the nudge. I (strongly) suspect that the issue is related to https://github.com/igrigorik/gharchive.org/issues/171. 

As the amount of overall GH activity continues to rise, the likelihood of us missing events is increasing because we're already hitting API quotas, and occasional activity spikes are another issue. To address this in a future-proof way, I think we need to rethink how we're collecting this data; I'd like to nudge us away from the polling solution. Of course, this route would require cooperation from the friendly GitHub crew. /cc @annafil @bkeepers

I propose we merge this thread into #171.

**Comment by lukaszgryglicki** [comment]
OK, cc @dankohn @jberkus.
let me know if I can help somehow.
maybe @dankohn can help with contacting GitHub/API limits issue?

**Comment by igrigorik** [comment]
Yep, Dan reached out over email and I've connected all the relevant parties there. Fingers crossed.
