### ISSUE TITLE
Is Data in BigQuery limited to certain licenses?

### ISSUE THREAD

**Issue by hamelsmu** [igrigorik/gharchive.org#206]
@igrigorik do you know if the data stored in BigQuery is limited to a subset of Licenses?   Or is it all code regardless of license, or just the presence of any license?  We are considering releasing an open source project based upon the data hosted there (machine learning).   

Thank you.

cc/: @hohsiangwu, @mlinksva, @bluemazzoo

**Comment by igrigorik** [comment]
We do not filter by license. GHArchive logs all data emitted by the [Events API](https://developer.github.com/v3/activity/events/), with obvious restriction that the associated event activity is only for public repositories on GitHub. 

Hope that answers your question? Feel free to reopen if otherwise.

**Comment by mlinksva** [comment]
FWIW the question was probably about github_repos in BigQuery which AFAIK is not part of GHArchive. Though I realize both are mentioned in https://github.blog/2016-06-29-making-open-source-data-more-available/ so it is easy to miss this. Please correct if I'm missing something! 😄
